# Generated by Django 2.1.5 on 2019-01-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistLinks', '0002_concert'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='last_updated',
            field=models.DateTimeField(default=None, verbose_name='last update'),
        ),
    ]
