# Generated by Django 2.1.5 on 2019-01-18 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistLinks', '0004_auto_20190118_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='Chicago', max_length=20),
        ),
    ]
