# Generated by Django 2.1.5 on 2019-02-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistLinks', '0006_concert_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='city',
            field=models.CharField(default='chicago', max_length=30),
        ),
    ]
